apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: NAMESPACE
  labels:
    app: web-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-tier
  template:
    metadata:
      labels:
        app: web-tier
    spec:
      containers:
      - name: web-container
        image: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/webapp:IMAGEVERSION
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: NAMESPACE
spec:
  selector:
    app: web-tier
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000