apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tier
  template:
    metadata:
      labels:
        app: api-tier
    spec:
      containers:
      - name: api-container
        image: 028615413248.dkr.ecr.us-east-1.amazonaws.com/apiapp:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-tier
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000